// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";
import { serverSchema } from "./src/env.schema";

const parsed = serverSchema.safeParse(process.env);

if (!parsed.success) {
  throw new Error("Invalid environment variables for Prisma");
}

export default defineConfig({
  schema: path.join(process.cwd(), "prisma"),
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: parsed.data.DATABASE_URL,
  },
});
