/**
 * Cross-cutting dashboard navigation copy (sidebar, breadcrumbs, manage tabs).
 */
export const dashboardNavLabels = {
  sidebar: {
    dashboard: "داشبورد",
    account: "حساب",
    organizationHome: "نمای کلی",
    notifications: "اعلان‌ها",
    organizationManagement: "مدیریت سازمان",
    groupOrganization: "سازمان",
    groupPlatform: "پلتفرم",
    adminUsers: "کاربران",
    adminOrganizations: "سازمان‌ها",
  },
  adminTabs: {
    users: "کاربران",
    organizations: "سازمان‌ها",
  },
  adminPage: {
    title: "مدیریت پلتفرم",
    description: "مدیریت کاربران و سازمان‌ها در سطح پلتفرم.",
  },
  accountSettings: {
    profile: "پروفایل",
    security: "رمز عبور",
    sessions: "نشست‌های فعال",
  },
  manageTabs: {
    members: "اعضا",
    teams: "تیم‌ها",
    teamMembers: "اعضای تیم",
    invitations: "دعوت‌نامه‌ها",
    notifications: "اعلان‌ها",
  },
  organizationManage: {
    editOrganization: "ویرایش سازمان",
    organizationName: "نام سازمان",
    organizationLogo: "آدرس لوگو",
    organizationLogoHint: "اختیاری. برای حذف لوگو خالی بگذارید.",
    saveOrganization: "ذخیره تغییرات",
  },
  teamManage: {
    allTeams: "همه تیم‌ها",
    manageMembers: "مدیریت اعضا",
    addTeam: "افزودن تیم",
    editTeam: "ویرایش تیم",
    deleteTeam: "حذف تیم",
    addMembers: "افزودن اعضا",
  },
  memberManage: {
    changeRole: "تغییر نقش",
    manageTeams: "مدیریت تیم‌ها",
    removeFromOrganization: "حذف از سازمان",
    removeFromTeam: "حذف از تیم",
  },
  viewProfile: {
    workspaces: "فضاهای کاری شما",
    openOrganization: "باز کردن سازمان",
    teamAccessOnly: "دسترسی تیمی",
    openTeam: "باز کردن تیم",
    organizations: "سازمان‌ها",
    yourTeams: "تیم‌ها",
    yourTeamsInOrganization: "تیم‌های شما",
    noOrganizations: "هنوز سازمانی ندارید",
    noTeams: "هنوز تیمی ندارید",
    noTeamsInOrganization: "تیمی در این سازمان نیست",
    manageOrganization: "مدیریت سازمان",
    manageTeams: "مدیریت تیم‌ها",
    manageTeam: "مدیریت تیم",
    members: "اعضا",
    teams: "تیم‌ها",
    joined: "عضو از",
    created: "ایجاد",
    teamInOrganization: "تیم در",
  },
  invitationManage: {
    deleteTitle: "حذف دعوت‌نامه",
    deleteDescription:
      "این لینک دعوت فوراً غیرفعال می‌شود. این کار قابل بازگشت نیست.",
    deleteConfirm: "حذف دعوت‌نامه",
  },
  adminUserManage: {
    changeRole: "تغییر نقش پلتفرم",
    banUser: "مسدود کردن کاربر",
    unbanUser: "رفع مسدودیت",
    banTitle: "مسدود کردن کاربر",
    banDescription: "این کاربر تا زمان رفع مسدودیت نمی‌تواند وارد شود.",
    banConfirm: "مسدود کردن",
  },
  breadcrumbSegments: {
    dashboard: "داشبورد",
    admin: "پلتفرم",
    users: "کاربران",
    organizations: "سازمان‌ها",
    account: "حساب",
    manage: "مدیریت",
    members: "اعضا",
    teams: "تیم‌ها",
    team: "تیم",
    invitations: "دعوت‌نامه‌ها",
    notifications: "اعلان‌ها",
  },
} as const;
